In [1]:
import pandas as pd
df=pd.read_csv("prices.csv")
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9     robbinsville   2600  575000
10    robbinsville   2900  600000
11    robbinsville   3100  620000
12    robbinsville   3600  695000

In [3]:
d=pd.get_dummies(df.town)

In [5]:
merged=pd.concat([df,d],axis="columns")
merged

,town,area,price,monroe township,robbinsville,west windsor
0,monroe township,2600,550000,True,False,False
1,monroe township,3000,565000,True,False,False
2,monroe township,3200,610000,True,False,False
3,monroe township,3600,680000,True,False,False
4,monroe township,4000,725000,True,False,False
5,west windsor,2600,585000,False,False,True
6,west windsor,2800,615000,False,False,True
7,west windsor,3300,650000,False,False,True
8,west windsor,3600,710000,False,False,True
9,robbinsville,2600,575000,False,True,False
10,robbinsville,2900,600000,False,True,False
11,robbinsville,3100,620000,False,True,False
12,robbinsville,3600,695000,False,True,False

In [13]:
merged["monroe township"]=merged["monroe township"].astype(int)
merged["robbinsville "]=merged["robbinsville "].astype(int)
merged["west windsor"]=merged["west windsor"].astype(int)
merged

,town,area,price,monroe township,robbinsville,west windsor
0,monroe township,2600,550000,1,0,0
1,monroe township,3000,565000,1,0,0
2,monroe township,3200,610000,1,0,0
3,monroe township,3600,680000,1,0,0
4,monroe township,4000,725000,1,0,0
5,west windsor,2600,585000,0,0,1
6,west windsor,2800,615000,0,0,1
7,west windsor,3300,650000,0,0,1
8,west windsor,3600,710000,0,0,1
9,robbinsville,2600,575000,0,1,0
10,robbinsville,2900,600000,0,1,0
11,robbinsville,3100,620000,0,1,0
12,robbinsville,3600,695000,0,1,0

In [14]:
final=merged.drop(["town","west windsor"],axis="columns")
final

    area   price  monroe township  robbinsville
0   2600  550000                1              0
1   3000  565000                1              0
2   3200  610000                1              0
3   3600  680000                1              0
4   4000  725000                1              0
5   2600  585000                0              0
6   2800  615000                0              0
7   3300  650000                0              0
8   3600  710000                0              0
9   2600  575000                0              1
10  2900  600000                0              1
11  3100  620000                0              1
12  3600  695000                0              1

In [16]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [17]:
X=final.drop("price",axis="columns")
X

    area  monroe township  robbinsville
0   2600                1              0
1   3000                1              0
2   3200                1              0
3   3600                1              0
4   4000                1              0
5   2600                0              0
6   2800                0              0
7   3300                0              0
8   3600                0              0
9   2600                0              1
10  2900                0              1
11  3100                0              1
12  3600                0              1

In [18]:
y=final.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [19]:
model.fit(X,y)

LinearRegression()

In [20]:
model.predict([[2800,0,1]])

/Users/sanchitajindal/Library/Python/3.9/lib/python/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([590775.63964739])

In [21]:
model.predict([[3400,0,0]])

/Users/sanchitajindal/Library/Python/3.9/lib/python/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([681241.66845839])

In [22]:
model.score(X,y)

0.9573929037221873

In [23]:
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9     robbinsville   2600  575000
10    robbinsville   2900  600000
11    robbinsville   3100  620000
12    robbinsville   3600  695000

In [25]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [27]:
dfle=df
dfle.town=le.fit_transform(dfle.town)
dfle

    town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [28]:
X=df[["town","area"]].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [29]:
y=dfle.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [33]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(categories=[0])

In [35]:
ohe.fit_transform(X).toarray()

ValueError: Expected 2D array, got 1D array instead:
array=[   0 2600].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.